---
# Vagrant installation

- name: Downloading vagrant
  become: True
  get_url:
    url: "https://releases.hashicorp.com/vagrant/{{ vagrant_release }}/{{ vagrant_dep_version }}.deb"
    dest: "{{ download_destination }}"
- name : Install vagrant
  become: True
  apt: deb="{{ download_destination }}/{{ vagrant_dep_version }}.deb"