---
- name: Add "deb https://dl.bintray.com/sbt/debian /" to /etc/apt/sources.list.d/sbt.list
  become: True
  shell: echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list

- name: Add apt-key
  become: True
  shell: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823

- name: Install sbt
  become: True
  apt:
   name: sbt
   state: latest
   update_cache: yes